### ISSUE TITLE
Other editors

### ISSUE THREAD

**Issue by ratmice** [ratmice/nimbleparse_lsp#1]
@ltratt you mentioned you don't use vscode, was curious which editor you do use
e.g. I haven't looked at emacs to see if it would be possible to get working with it.

The general mechanism this works with is:
register a workspace style project based on '**/nimbleparse.toml', when the editor finds that, it calls `activate` which reads `nimbleparse.toml` and pulls out the appropriate file extension for test input.

I don't really use vscode either, but it was the first editor I found which could support this dynamic extension registration.

**Comment by ltratt** [comment]
I'm using neovim (with LSP support).

**Comment by ratmice** [comment]
Ahh yeah, that is what I usually use too, but afaict it only supports static extenstion registration and minimal workspace support.
So it'll probably take some work in neovim to get it working there, but it isn't anything i've looked at in depth yet.

**Comment by ratmice** [comment]
Not really important, but 

I updated the instructions for instructions which shows a manual configuration for neovim.
it can't automatically deduce file extensions from nimbleparse.lsp.  However you can hard code them.

Currently that works, the example setup in [neovim/README.md](https://github.com/ratmice/nimbleparse_lsp/tree/main/neovim)
sets up extensions as expected by https://github.com/ratmice/crimson/

there isn't much visible output within neovim at this point, so you'll probably have to `tail -f /path/to/lsp.log` listed in the Testing section.  It is *real* slow, but eventually it should parse through all the tests on change of either test input or `.l`, or `.y`

Unfortunately because of some sync issues, it isn't possible currently to emit anything until after it has parsed *all* the files.

Anyhow that is the current status at this time.

**Comment by ratmice** [comment]
Cool, going to close this for now if anyone has any other editors they want to discuss feel free to reopen or open an editor specific issue.
